name: tf
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - ca-certificates=2024.7.2
  - comm=0.2.2
  - cuda-nvcc=11.3.58
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.38
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=13.2.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.0
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.9.19
  - python-dateutil=2.9.0
  - python_abi=3.9
  - pyzmq=26.0.3
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - antiorm==1.2.1
      - astunparse==1.6.3
      - blinker==1.8.2
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - db==0.1.1
      - db-sqlite3==0.0.1
      - flask==3.0.3
      - flask-cors==4.0.1
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - gast==0.4.0
      - google-auth==2.29.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - h5py==3.11.0
      - idna==3.7
      - importlib-resources==6.4.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - keras==2.11.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pillow==10.3.0
      - protobuf==3.19.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyparsing==3.1.2
      - python-dotenv==1.0.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.1
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - typing-extensions==4.12.0
      - urllib3==2.2.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - zipp==3.19.0

